#' Add emmeans pairwise comparison brackets to a ggplot
#'
#' `add_emmeans_pbars()` adds significance brackets to an existing ggplot using
#' pairwise comparisons generated by `emmeans::pairs()` or `emmeans::contrast()`.
#' It is designed to make model-derived post hoc comparisons easier to display
#' on ggplots, especially when plots include facets, nested facets, fill/color
#' aesthetics, or dodged geoms.
#'
#' The function uses the ggplot object to infer the x aesthetic, y aesthetic,
#' fill/color aesthetics, facet variables, dodged group positions, and
#' panel-specific y ranges. It then uses the emmeans contrast table to infer
#' group1, group2, p.value, and comparison context, and passes a cleaned
#' annotation table to [ggpubr::stat_pvalue_manual()].
#'
#' **Recommended emmeans pattern:**
#'
#' ```r
#' emmeans(model, ~ variable_being_compared | variables_that_define_context) |>
#'   pairs()
#' ```
#'
#' Variables after `|` should include everything needed to identify where each
#' comparison belongs in the plot (facet variables, x-axis context, etc.).
#'
#' @param p A ggplot object. Must contain data and define both x and y
#'   aesthetics in the main `ggplot(aes(...))` call.
#' @param contrasts An object returned by `emmeans::pairs()` or
#'   `emmeans::contrast()`. Must contain a `contrast` column and a `p.value`
#'   column after conversion with [as.data.frame()].
#' @param y_offset Numeric. Fraction of the local y-range used to place the
#'   first significance bracket above the data. Default is `0.05`.
#' @param step.increase Numeric. Fraction of the local y-range used to
#'   vertically separate multiple brackets within the same panel or grouping
#'   context. Default is `0.08`.
#' @param dodge_width Numeric. Width used to calculate bracket positions for
#'   dodged geoms, such as `geom_boxplot(aes(fill = group))`. Default is
#'   `0.75`, which matches the default boxplot dodge width.
#' @param label Character. Label style for the brackets. One of:
#'   - `"stars"` for significance stars (default)
#'   - `"p.format"` for formatted p-values
#'   - `"p.value"` for raw p-values
#' @param hide.ns Logical. If `TRUE` (default), nonsignificant comparisons
#'   (p >= 0.05) are removed before plotting.
#' @param y_col Character. The name of the column in the ggplot data
#'   containing the group means (y-axis values). If `NULL` (default), the
#'   means column is inferred from the plot's y aesthetic.
#' @param step_height_col Character. The name of the column in the contrasts
#'   data frame to use as the baseline y-height for each bracket. If `NULL`
#'   (default), the function checks for `"upper.CL"` in the contrasts data
#'   frame; if found, it uses that; otherwise, it falls back to the data's
#'   maximum y-value.
#' @param ... Additional arguments passed to [ggpubr::stat_pvalue_manual()].
#'
#' @return A ggplot object with significance brackets added.
#'
#' @details
#' The function supports these common plotting structures:
#'
#' 1. **Simple x-axis comparisons.**
#'    `ggplot(aes(Cell, Area))`
#'
#' 2. **Faceted x-axis comparisons.**
#'    `ggplot(aes(Cell, Area)) + facet_wrap(~ Spheroid)`
#'
#' 3. **Multiple or nested facets.**
#'    `facet_nested_wrap(~ Spheroid + Matrix)`
#'
#' 4. **Dodged fill/color plots.**
#'    `ggplot(aes(Cell, Area, fill = Spheroid))`
#'
#' 5. **Fill/color comparisons within an x-axis category.**
#'    `ggplot(aes(Spheroid, Area, fill = Cell))`
#'
#' For best results the emmeans structure should mirror the plot structure:
#' the variable being compared appears before `|`, and variables defining
#' facets, dodges, or panel context appear after `|`.
#'
#' @examples
#' \dontrun{
#' # Simple x-axis comparison
#' emm <- emmeans(fit, ~ Cell) |> pairs()
#' p   <- df |> ggplot(aes(Cell, Area)) + geom_boxplot()
#' add_emmeans_pbars(p, emm)
#'
#' # Faceted comparison
#' emm <- emmeans(fit, ~ Cell | Spheroid) |> pairs()
#' p   <- df |>
#'   ggplot(aes(Cell, Area)) +
#'   geom_boxplot() +
#'   facet_wrap(~ Spheroid)
#' add_emmeans_pbars(p, emm)
#'
#' # Dodged fill comparison
#' emm <- emmeans(fit, ~ Cell | Spheroid) |> pairs()
#' p   <- df |> ggplot(aes(Cell, Area, fill = Spheroid)) + geom_boxplot()
#' add_emmeans_pbars(p, emm)
#'
#' # Fill-group comparison within each x-axis level
#' emm <- emmeans(fit, ~ Cell | Spheroid) |> pairs()
#' p   <- df |> ggplot(aes(Spheroid, Area, fill = Cell)) + geom_boxplot()
#' add_emmeans_pbars(p, emm)
#'
#' # Adjust bracket placement
#' add_emmeans_pbars(p, emm, y_offset = 0.10, step.increase = 0.12)
#'
#' # Show formatted p-values instead of stars
#' add_emmeans_pbars(p, emm, label = "p.format")
#'
#' # Show all comparisons including nonsignificant
#' add_emmeans_pbars(p, emm, hide.ns = FALSE)
#'
#' # Match a custom dodge width
#' p2 <- df |>
#'   ggplot(aes(Cell, Area, fill = Spheroid)) +
#'   geom_boxplot(position = position_dodge(width = 0.8))
#' add_emmeans_pbars(p2, emm, dodge_width = 0.8)
#' }
#'
#' @importFrom dplyr %>% mutate filter group_by summarise ungroup left_join
#'   distinct across all_of if_else row_number case_when
#' @importFrom tidyr separate
#' @importFrom rlang as_name eval_tidy
#' @importFrom ggpubr stat_pvalue_manual
#' @export
add_emmeans_pbars <- function(
  p,
  contrasts,
  y_offset = 0.05,
  step.increase = 0.08,
  dodge_width = 0.75,
  label = c("stars", "p.format", "p.value"),
  hide.ns = TRUE,
  y_col = NULL,
  step_height_col = NULL,
  ...
) {
  label <- match.arg(label)

  data <- p$data

  if (is.null(data)) {
    stop("The ggplot object must contain data.")
  }

  if (is.null(p$mapping$x) || (is.null(p$mapping$y) && is.null(y_col))) {
    stop("Could not infer x and y aesthetics from the ggplot object. Specify `y_col` if the y aesthetic is missing or complex.")
  }

  clean_label <- function(x) {
    x <- as.character(x)
    x <- trimws(x)
    x <- gsub("^`|`$", "", x)
    x <- gsub("^\\(|\\)$", "", x)
    x <- gsub("\\s+", " ", x)
    x
  }

  get_levels <- function(x) {
    if (is.factor(x)) levels(x) else unique(as.character(x))
  }

  match_to_levels <- function(values, levels) {
    values_chr <- as.character(values)
    levels_chr <- as.character(levels)

    idx <- match(values_chr, levels_chr)
    if (all(!is.na(idx))) return(idx)

    idx <- match(clean_label(values_chr), clean_label(levels_chr))
    if (all(!is.na(idx))) return(idx)

    match(tolower(clean_label(values_chr)), tolower(clean_label(levels_chr)))
  }

  all_match_levels <- function(values, levels) {
    all(!is.na(match_to_levels(values, levels)))
  }

  get_plot_facet_vars <- function(p) {
    vars   <- character(0)
    params <- p$facet$params

    if (!is.null(params$facets)) vars <- c(vars, names(params$facets))
    if (!is.null(params$rows))   vars <- c(vars, names(params$rows))
    if (!is.null(params$cols))   vars <- c(vars, names(params$cols))

    unique(vars[nzchar(vars)])
  }

  make_key <- function(df, vars) {
    if (length(vars) == 0) return(rep(".__single__.", nrow(df)))
    do.call(paste, c(lapply(vars, function(v) clean_label(df[[v]])), sep = "\r"))
  }

  get_dodge_table <- function(data, vars) {
    if (length(vars) == 0) {
      return(data.frame(.key = ".__single__.", .offset = 0))
    }

    level_list        <- lapply(vars, function(v) get_levels(data[[v]]))
    names(level_list) <- vars

    combos  <- expand.grid(level_list, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    present <- data %>% distinct(across(all_of(vars)))

    combos$.key  <- make_key(combos, vars)
    present$.key <- make_key(present, vars)
    combos       <- combos[combos$.key %in% present$.key, , drop = FALSE]

    n <- nrow(combos)
    if (n == 0) stop("Could not infer dodge groups from the plot data.")

    combos$.offset <- (seq_len(n) - (n + 1) / 2) * dodge_width / n
    combos
  }

  lookup_dodge_offset <- function(df, vars, dodge_table) {
    if (length(vars) == 0) return(rep(0, nrow(df)))

    keys <- make_key(df, vars)
    idx  <- match(keys, dodge_table$.key)

    if (any(is.na(idx))) {
      stop(
        "Could not match one or more emmeans rows to dodged ggplot positions. ",
        "Check that the emmeans conditioning variables match the plot fill/color variables."
      )
    }

    dodge_table$.offset[idx]
  }

  # --- Infer plot structure --------------------------------------------------

  x_var <- as_name(p$mapping$x)

  group_vars <- character(0)
  if (!is.null(p$mapping$fill))   group_vars <- c(group_vars, as_name(p$mapping$fill))
  if (!is.null(p$mapping$colour)) group_vars <- c(group_vars, as_name(p$mapping$colour))
  if (!is.null(p$mapping$color))  group_vars <- c(group_vars, as_name(p$mapping$color))
  group_vars <- unique(group_vars)
  group_vars <- group_vars[group_vars %in% names(data)]

  plot_facet_vars <- get_plot_facet_vars(p)

  if (is.null(y_col)) {
    data$.emm_y  <- eval_tidy(p$mapping$y, data = data)
  } else {
    if (!y_col %in% names(data)) {
      stop(sprintf("The specified `y_col` ('%s') was not found in the ggplot data.", y_col))
    }
    data$.emm_y <- data[[y_col]]
  }
  data_for_y   <- data %>% filter(is.finite(.emm_y))

  if (nrow(data_for_y) == 0) {
    stop("No finite y-values were found in the ggplot data column for the y-axis.")
  }

  # --- Parse contrast table --------------------------------------------------

  out <- as.data.frame(contrasts)

  if (!"contrast" %in% names(out)) stop("Input must contain a `contrast` column.")
  if (!"p.value"  %in% names(out)) stop("Input must contain a `p.value` column.")

  height_col <- NULL
  if (!is.null(step_height_col)) {
    if (!step_height_col %in% names(out)) {
      stop(sprintf("The specified `step_height_col` ('%s') was not found in the contrasts data frame.", step_height_col))
    }
    height_col <- step_height_col
  } else if ("upper.CL" %in% names(out)) {
    height_col <- "upper.CL"
  }

  out <- out %>%
    tidyr::separate(
      contrast,
      into  = c("group1", "group2"),
      sep   = "\\s+[-/]\\s+",
      remove = FALSE
    ) %>%
    mutate(
      group1   = clean_label(group1),
      group2   = clean_label(group2),
      p.signif = case_when(
        p.value < 0.001 ~ "***",
        p.value < 0.01  ~ "**",
        p.value < 0.05  ~ "*",
        TRUE            ~ "ns"
      ),
      p.format = format.pval(p.value, digits = 2, eps = 0.001)
    )

  if (hide.ns) out <- out %>% filter(p.value < 0.05)
  if (nrow(out) == 0) return(p)

  out$label <- switch(
    label,
    stars    = out$p.signif,
    p.format = paste0("p = ", out$p.format),
    p.value  = as.character(out$p.value)
  )

  # --- Determine comparison axis ---------------------------------------------

  x_levels       <- get_levels(data[[x_var]])
  contrast_levels <- unique(c(out$group1, out$group2))
  contrast_is_x  <- all_match_levels(contrast_levels, x_levels)

  matching_group_vars <- group_vars[
    vapply(group_vars, function(g) all_match_levels(contrast_levels, get_levels(data[[g]])), logical(1))
  ]

  if (!contrast_is_x && length(matching_group_vars) == 0) {
    stop(
      "Contrast labels do not match the x-axis or any fill/color grouping variable.\n",
      "Contrast labels: ", paste(contrast_levels, collapse = ", "), "\n",
      "x-axis levels for `", x_var, "`: ", paste(x_levels, collapse = ", ")
    )
  }

  if (length(matching_group_vars) > 1 && !contrast_is_x) {
    stop(
      "Contrast labels match more than one grouping aesthetic: ",
      paste(matching_group_vars, collapse = ", "),
      ". Specify the intended emmeans contrast structure more explicitly."
    )
  }

  grouped_comparison <- length(matching_group_vars) == 1 && !contrast_is_x

  meta_cols    <- c("contrast", "group1", "group2", "p.value", "p.signif", "p.format", "label")
  context_vars <- intersect(names(out), names(data))
  context_vars <- setdiff(context_vars, meta_cols)

  # Exclude common statistical summary columns from context_vars
  stat_cols <- c(
    "SE", "df", "lower.CL", "upper.CL", "estimate", "emmean", "t.ratio", "z.ratio",
    "std.error", "statistic", "p.value", "LCL", "UCL", "as.LCL", "as.UCL",
    "lower", "upper", "ratio", "response", "null", "log.ratio"
  )
  context_vars <- setdiff(context_vars, c(stat_cols, step_height_col))

  out$xmin <- out$group1
  out$xmax <- out$group2

  # --- Compute x positions ---------------------------------------------------

  if (contrast_is_x) {
    active_dodge_vars <- setdiff(intersect(group_vars, names(out)), plot_facet_vars)

    x1 <- match_to_levels(out$group1, x_levels)
    x2 <- match_to_levels(out$group2, x_levels)

    if (any(is.na(x1)) || any(is.na(x2))) {
      stop(
        "Could not match contrast labels to x-axis levels after normalization.\n",
        "Contrast labels: ", paste(contrast_levels, collapse = ", "), "\n",
        "x-axis levels for `", x_var, "`: ", paste(x_levels, collapse = ", ")
      )
    }

    if (length(active_dodge_vars) > 0) {
      dodge_table  <- get_dodge_table(data, active_dodge_vars)
      dodge_offset <- lookup_dodge_offset(out, active_dodge_vars, dodge_table)
      out$xmin <- x1 + dodge_offset
      out$xmax <- x2 + dodge_offset
    } else {
      out$xmin <- x1
      out$xmax <- x2
    }

  } else if (grouped_comparison) {
    contrast_group_var <- matching_group_vars[1]

    x_context_candidates <- context_vars[
      vapply(context_vars, function(v) all_match_levels(out[[v]], x_levels), logical(1))
    ]

    if (length(x_context_candidates) != 1) {
      stop(
        "Detected a fill/color comparison, but could not infer the x variable from the emmeans output. ",
        "Use emmeans(model, ~ fill_or_color_group | x_var + facet_var) %>% pairs()."
      )
    }

    x_context_var     <- x_context_candidates[1]
    active_dodge_vars <- setdiff(group_vars, plot_facet_vars)

    missing_dodge_vars <- setdiff(active_dodge_vars, c(contrast_group_var, names(out)))
    if (length(missing_dodge_vars) > 0) {
      stop(
        "Cannot infer dodge positions because these grouping variables are not present in the emmeans output: ",
        paste(missing_dodge_vars, collapse = ", ")
      )
    }

    dodge_table <- get_dodge_table(data, active_dodge_vars)

    key1 <- out
    key2 <- out
    for (v in active_dodge_vars) {
      if (v == contrast_group_var) {
        key1[[v]] <- out$group1
        key2[[v]] <- out$group2
      }
    }

    base_x <- match_to_levels(out[[x_context_var]], x_levels)
    if (any(is.na(base_x))) stop("Could not match emmeans x-context values to x-axis levels.")

    out$xmin <- base_x + lookup_dodge_offset(key1, active_dodge_vars, dodge_table)
    out$xmax <- base_x + lookup_dodge_offset(key2, active_dodge_vars, dodge_table)
  }

  # --- Compute y positions ---------------------------------------------------

  y_group_vars <- context_vars[
    context_vars %in% names(data_for_y) & context_vars %in% names(out)
  ]

  if (length(y_group_vars) > 0) {
    y_lims <- data_for_y %>%
      group_by(across(all_of(y_group_vars))) %>%
      summarise(
        y_max = max(.emm_y, na.rm = TRUE),
        y_min = min(.emm_y, na.rm = TRUE),
        .groups = "drop"
      ) %>%
      mutate(
        y_range = y_max - y_min,
        y_range = if_else(is.finite(y_range) & y_range > 0, y_range, 1)
      )

    out <- out %>%
      left_join(y_lims, by = y_group_vars) %>%
      group_by(across(all_of(y_group_vars)))

    if (!is.null(height_col)) {
      out <- out %>%
        mutate(
          y.position = if_else(is.na(.data[[height_col]]), y_max, .data[[height_col]]) + y_range * y_offset + (row_number() - 1) * y_range * step.increase
        )
    } else {
      out <- out %>%
        mutate(
          y.position = y_max + y_range * y_offset + (row_number() - 1) * y_range * step.increase
        )
    }

    out <- out %>% ungroup()
  } else {
    y_max   <- max(data_for_y$.emm_y, na.rm = TRUE)
    y_min   <- min(data_for_y$.emm_y, na.rm = TRUE)
    y_range <- y_max - y_min
    if (!is.finite(y_range) || y_range <= 0) y_range <- 1

    if (!is.null(height_col)) {
      out <- out %>%
        mutate(
          y.position = if_else(is.na(.data[[height_col]]), y_max, .data[[height_col]]) + y_range * y_offset + (row_number() - 1) * y_range * step.increase
        )
    } else {
      out <- out %>%
        mutate(
          y.position = y_max + y_range * y_offset + (row_number() - 1) * y_range * step.increase
        )
    }
  }

  out <- out %>% filter(is.finite(y.position))
  if (nrow(out) == 0) return(p)

  # --- Add brackets to plot --------------------------------------------------

  p + stat_pvalue_manual(
    out,
    label      = "label",
    xmin       = "xmin",
    xmax       = "xmax",
    y.position = "y.position",
    inherit.aes = FALSE,
    hide.ns    = FALSE,
    ...
  )
}
